### ISSUE TITLE
Mockup Epic

### ISSUE THREAD

**Issue by BrianDavidAllen** [ewb-psu/shelter-project#26]
## Description 
This contains all the components we think are needed to complete the mockup. It is crucial to our success to keep this issue up-to-date. 

## Acceptance Criteria 
- [ ] Content page
- [ ] Mutually exclusive buttons
- [ ] Multi select buttons
- [ ] Input field
- [ ] Shelter info container 
- [ ] Shelter sidebar
- [ ] Home sidebar
